Bag:
  C1:
    DisplayName: "Blocs de construction"
    DisplayItem: bricks
    Position: 10
    Items:
      - acacia_log
      - acacia_planks
      - acacia_slab
      - acacia_stairs
  C2:
    DisplayName: "Blocs de décoration"
    DisplayItem: peony
    Position: 12
    Items:
      - acacia_fence
      - acacia_leaves
      - acacia_sapling
      - allium
      - anvil
      - armor_stand
      - azure_bluet
  C3:
    DisplayName: "Minerais"
    DisplayItem: diamond
    Position: 14
    Items:
      - coal_block
      - diamond_block
  C4:
    DisplayName: "Loot"
    DisplayItem: bone
    Position: 16
    Items:
      - bone
      - gun_powder
  C5:
    DisplayName: "Verres"
    DisplayItem: glass
    Position: 18
    Items:
      - GLASS
  C6:
    DisplayName: "Combat"
    DisplayItem: diamond_sword
    Position: 20
    Items:
      - DIAMOND_SWORD
  C7:
    DisplayName: "Livres"
    DisplayItem: book
    Position: 22
    Items:
      - BOOK
  C8:
    DisplayName: "Nourriture"
    DisplayItem: apple
    Position: 24
    Items:
      - APPLE
  C9:
    DisplayName: "Transportation"
    DisplayItem: elytra
    Position: 26
    Items:
      - ELYTRA